name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fair: ^4.0.0
  fair_pushy:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  fair_compiler: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/fair_basic_config.json
    - build/
    - build/fair/
