name: fair_pushy
description: fair_pushy is a hot update sdk for fair
version: 0.0.1
homepage: https://github.com/wuba/FairPushy/tree/main/sdk

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15   #文件路径相关
  archive: ^3.6.1  #压缩，解压缩相关
  permission_handler: ^12.0.1
  dio: ^5.9.2
  shared_preferences: ^2.5.3
  #摇一摇重力感应
  sensors_plus: ^7.0.0
  #扫描二维码
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.test.fair_pushy
    iosBundleIdentifier: com.test.fair_pushy
